-- 코드를 작성해주세요
SELECT T.ITEM_ID AS ITEM_ID, PI.ITEM_NAME, PI.RARITY
FROM ITEM_INFO AS I, ITEM_TREE AS T, ITEM_INFO AS PI
WHERE T.PARENT_ITEM_ID = I.ITEM_ID AND I.RARITY = 'RARE' AND T.ITEM_ID = PI.ITEM_ID
ORDER BY T.ITEM_ID DESC
